=== gfauredev/free-exercise-db/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[0-9a-z_]+$"
    },
    "name": {
      "type": "string"
    },
    "force": {
      "type": "string",
      "enum": [
        "static",
        "pull",
        "push"
      ]
    },
    "level": {
      "type": "string",
      "enum": [
        "beginner",
        "intermediate",
        "expert"
      ]
    },
    "mechanic": {
      "type": "string",
      "enum": [
        "isolation",
        "compound"
      ]
    },
    "equipment": {
      "type": "string",
      "enum": [
        "medicine ball",
        "dumbbell",
        "bands",
        "kettlebells",
        "foam roll",
        "cable",
        "machine",
        "barbell",
        "exercise ball",
        "e-z curl bar",
        "other"
      ]
    },
    "primaryMuscles": {
      "type": "array",
      "items": [
        {
          "type": "string",
          "enum": [
            "abdominals",
            "abductors",
            "adductors",
            "biceps",
            "calves",
            "chest",
            "forearms",
            "glutes",
            "hamstrings",
            "lats",
            "lower back",
            "middle back",
            "neck",
            "quadriceps",
            "shoulders",
            "traps",
            "triceps"
          ]
        }
      ]
    },
    "secondaryMuscles": {
      "type": "array",
      "items": [
        {
          "type": "string",
          "enum": [
            "abdominals",
            "abductors",
            "adductors",
            "biceps",
            "calves",
            "chest",
            "forearms",
            "glutes",
            "hamstrings",
            "lats",
            "lower back",
            "middle back",
            "neck",
            "quadriceps",
            "shoulders",
            "traps",
            "triceps"
          ]
        }
      ]
    },
    "instructions": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "category": {
      "type": "string",
      "enum": [
        "powerlifting",
        "strength",
        "stretching",
        "cardio",
        "olympic weightlifting",
        "strongman",
        "plyometrics"
      ]
    },
    "images": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "id",
    "name",
    "force",
    "level",
    "mechanic",
    "primaryMuscles",
    "secondaryMuscles",
    "instructions",
    "category",
    "images"
  ]
}

=== gfauredev/free-exercise-db/exercises/All_Fours_Quad_Stretch.json
{
  "name": "All Fours Quad Stretch",
  "force": "static",
  "level": "intermediate",
  "mechanic": "isolation",
  "primaryMuscles": [
    "quadriceps"
  ],
  "secondaryMuscles": [
    "quadriceps"
  ],
  "instructions": [
    "Start off on your hands and knees, then lift your leg off the floor and hold the foot with your hand.",
    "Use your hand to hold the foot or ankle, keeping the knee fully flexed, stretching the quadriceps and hip flexors.",
    "Focus on extending your hips, thrusting them towards the floor. Hold for 10-20 seconds and then switch sides."
  ],
  "category": "stretching",
  "images": [
    "All_Fours_Quad_Stretch/0.jpg",
    "All_Fours_Quad_Stretch/1.jpg"
  ],
  "id": "all_fours_quad_stretch"
}

=== gfauredev/free-exercise-db/exercises/Seated_Dumbbell_Inner_Biceps_Curl.json
{
  "name": "Seated Dumbbell Inner Biceps Curl",
  "force": "pull",
  "level": "beginner",
  "mechanic": "isolation",
  "equipment": "dumbbell",
  "primaryMuscles": [
    "biceps"
  ],
  "secondaryMuscles": [],
  "instructions": [
    "Sit on the end of a flat bench with a dumbbell in each hand being held at arms length. The elbows should be close to the torso.",
    "Rotate the palms of the hands so that they are facing inward in a neutral position. This will be your starting position.",
    "While holding the upper arms stationary, curl the dumbbells out and up, turning the palms out as you lift and keeping your forearms in line with your outer deltoids. Tips:",
    "Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps.",
    "Slowly begin to bring the dumbbells back to the starting position as your breathe in. Remember to rotate your arms as you lower the dumbbells so that you can switch back to a neutral grip.",
    "Repeat for the recommended amount of repetitions."
  ],
  "category": "strength",
  "images": [
    "Seated_Dumbbell_Inner_Biceps_Curl/0.jpg",
    "Seated_Dumbbell_Inner_Biceps_Curl/1.jpg"
  ],
  "id": "seated_dumbbell_inner_biceps_curl"
}

=== gfauredev/free-exercise-db/exercises/one_arm_lat_pulldown.json
{
  "name": "One Arm Lat Pulldown",
  "force": "pull",
  "level": "beginner",
  "mechanic": "compound",
  "equipment": "cable",
  "primaryMuscles": [
    "lats"
  ],
  "secondaryMuscles": [
    "biceps",
    "middle back"
  ],
  "instructions": [
    "Select an appropriate weight and adjust the knee pad to help keep you down. Grasp the handle with a pronated grip. This will be your starting position.",
    "Pull the handle down, squeezing your elbow to your side as you flex the elbow.",
    "Pause at the bottom of the motion, and then slowly return the handle to the starting position.",
    "For multiple repetitions, avoid completely returning the weight to keep tension on the muscles being worked."
  ],
  "category": "strength",
  "images": [
    "one_arm_lat_pulldown/0.jpg",
    "one_arm_lat_pulldown/1.jpg"
  ],
  "id": "one_arm_lat_pulldown"
}

=== gfauredev/free-exercise-db/exercises/Bodyweight_Squat.json
{
  "name": "Bodyweight Squat",
  "force": "push",
  "level": "beginner",
  "mechanic": "compound",
  "primaryMuscles": [
    "quadriceps"
  ],
  "secondaryMuscles": [
    "glutes",
    "hamstrings"
  ],
  "instructions": [
    "Stand with your feet shoulder width apart. You can place your hands behind your head. This will be your starting position.",
    "Begin the movement by flexing your knees and hips, sitting back with your hips.",
    "Continue down to full depth if you are able,and quickly reverse the motion until you return to the starting position. As you squat, keep your head and chest up and push your knees out."
  ],
  "category": "strength",
  "images": [
    "Bodyweight_Squat/0.jpg",
    "Bodyweight_Squat/1.jpg"
  ],
  "id": "bodyweight_squat"
}

=== gfauredev/free-exercise-db/exercises/one_arm_kettlebell_para_press.json
{
  "name": "One-Arm Kettlebell Para Press",
  "force": "push",
  "level": "intermediate",
  "mechanic": "compound",
  "equipment": "kettlebells",
  "primaryMuscles": [
    "shoulders"
  ],
  "secondaryMuscles": [
    "triceps"
  ],
  "instructions": [
    "Clean a kettlebell to your shoulder. Clean the kettlebell to your shoulder by extending through the legs and hips as you pull the kettlebell towards your shoulder. Rotate your wrist as you do so, so that the palm faces forward. This will be your starting position.",
    "Hold the kettlebell with the elbow out to the side, and press it up and out until it is locked out overhead.",
    "Lower the kettlebell back to your shoulder under control and repeat. Make sure to contract your lat, butt, and stomach forcefully for added stability and strength."
  ],
  "category": "strength",
  "images": [
    "one_arm_kettlebell_para_press/0.avif",
    "one_arm_kettlebell_para_press/1.avif"
  ],
  "id": "one_arm_kettlebell_para_press"
}

=== gfauredev/free-exercise-db/exercises/Moving_Claw_Series.json
{
  "name": "Moving Claw Series",
  "force": "push",
  "level": "beginner",
  "mechanic": "compound",
  "primaryMuscles": [
    "hamstrings"
  ],
  "secondaryMuscles": [
    "calves",
    "quadriceps"
  ],
  "instructions": [
    "This move helps prepare your running form to help you excel at sprinting. As you run, be sure to flex the knee, aiming to kick your glutes as the hip extends.",
    "Reload the quad as the leg moves back forward, attacking the ground on the next step.",
    "Ensure that as you run, you block with the arms, punching through in a rapid 1-2 motion."
  ],
  "category": "plyometrics",
  "images": [
    "Moving_Claw_Series/0.jpg",
    "Moving_Claw_Series/1.jpg"
  ],
  "id": "moving_claw_series"
}

=== gfauredev/free-exercise-db/exercises/bent_over_two_dumbbell_row_with_palms_in.json
{
  "name": "Bent Over Two-Dumbbell Row with Palms in",
  "force": "pull",
  "level": "beginner",
  "mechanic": "compound",
  "equipment": "dumbbell",
  "primaryMuscles": [
    "middle back"
  ],
  "secondaryMuscles": [
    "biceps",
    "lats"
  ],
  "instructions": [
    "With a dumbbell in each hand (palms facing each other), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The weights should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.",
    "While keeping the torso stationary, lift the dumbbells to your side as you breathe out, squeezing your shoulder blades together. On the top contracted position, squeeze the back muscles and hold for a second.",
    "Slowly lower the weight again to the starting position as you inhale.",
    "Repeat for the recommended amount of repetitions."
  ],
  "category": "strength",
  "images": [
    "bent_over_two_dumbbell_row_with_palms_in/0.avif",
    "bent_over_two_dumbbell_row_with_palms_in/1.avif"
  ],
  "id": "bent_over_two_dumbbell_row_with_palms_in"
}

=== gfauredev/free-exercise-db/exercises/Cable_Chest_Press.json
{
  "name": "Cable Chest Press",
  "force": "push",
  "level": "beginner",
  "mechanic": "compound",
  "equipment": "cable",
  "primaryMuscles": [
    "chest"
  ],
  "secondaryMuscles": [
    "shoulders",
    "triceps"
  ],
  "instructions": [
    "Adjust the weight to an appropriate amount and be seated, grasping the handles. Your upper arms should be about 45 degrees to the body, with your head and chest up. The elbows should be bent to about 90 degrees. This will be your starting position.",
    "Begin by extending through the elbow, pressing the handles together straight in front of you. Keep your shoulder blades retracted as you execute the movement.",
    "After pausing at full extension, return to th starting position, keeping tension on the cables.",
    "You can also execute this movement with your back off the pad, at an incline or decline, or alternate hands."
  ],
  "category": "strength",
  "images": [
    "Cable_Chest_Press/0.jpg",
    "Cable_Chest_Press/1.jpg"
  ],
  "id": "cable_chest_press"
}
