=== gfauredev/free-exercise-db/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[0-9a-z_]+$"
    },
    "name": {
      "type": "string"
    },
    "force": {
      "type": "string",
      "enum": [
        "static",
        "pull",
        "push"
      ]
    },
    "level": {
      "type": "string",
      "enum": [
        "beginner",
        "intermediate",
        "expert"
      ]
    },
    "mechanic": {
      "type": "string",
      "enum": [
        "isolation",
        "compound"
      ]
    },
    "equipment": {
      "type": "string",
      "enum": [
        "medicine ball",
        "dumbbell",
        "bands",
        "kettlebells",
        "foam roll",
        "cable",
        "machine",
        "barbell",
        "exercise ball",
        "e-z curl bar",
        "other"
      ]
    },
    "primaryMuscles": {
      "type": "array",
      "items": [
        {
          "type": "string",
          "enum": [
            "abdominals",
            "abductors",
            "adductors",
            "biceps",
            "calves",
            "chest",
            "forearms",
            "glutes",
            "hamstrings",
            "lats",
            "lower back",
            "middle back",
            "neck",
            "quadriceps",
            "shoulders",
            "traps",
            "triceps"
          ]
        }
      ]
    },
    "secondaryMuscles": {
      "type": "array",
      "items": [
        {
          "type": "string",
          "enum": [
            "abdominals",
            "abductors",
            "adductors",
            "biceps",
            "calves",
            "chest",
            "forearms",
            "glutes",
            "hamstrings",
            "lats",
            "lower back",
            "middle back",
            "neck",
            "quadriceps",
            "shoulders",
            "traps",
            "triceps"
          ]
        }
      ]
    },
    "instructions": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "category": {
      "type": "string",
      "enum": [
        "powerlifting",
        "strength",
        "stretching",
        "cardio",
        "olympic weightlifting",
        "strongman",
        "plyometrics"
      ]
    },
    "images": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "id",
    "name",
    "force",
    "level",
    "mechanic",
    "primaryMuscles",
    "secondaryMuscles",
    "instructions",
    "category",
    "images"
  ]
}

=== gfauredev/free-exercise-db/exercises/Weighted_Ball_Hyperextension.json
{
  "name": "Weighted Ball Hyperextension",
  "force": "pull",
  "level": "intermediate",
  "mechanic": "compound",
  "equipment": "exercise ball",
  "primaryMuscles": [
    "lower back"
  ],
  "secondaryMuscles": [
    "glutes",
    "hamstrings",
    "middle back"
  ],
  "instructions": [
    "To begin, lie down on an exercise ball with your torso pressing against the ball and parallel to the floor. The ball of your feet should be pressed against the floor to help keep you balanced. Place a weighted plate under your chin or behind your neck. This is the starting position.",
    "Slowly raise your torso up by bending at the waist and lower back. Remember to exhale during this movement.",
    "Hold the contraction on your lower back for a second and lower your torso back down to the starting position while inhaling.",
    "Repeat for the recommended amount of repetitions prescribed in your program."
  ],
  "category": "strength",
  "images": [
    "Weighted_Ball_Hyperextension/0.jpg",
    "Weighted_Ball_Hyperextension/1.jpg"
  ],
  "id": "weighted_ball_hyperextension"
}

=== gfauredev/free-exercise-db/exercises/Smith_Machine_Behind_the_Back_Shrug.json
{
  "name": "Smith Machine Behind the Back Shrug",
  "force": "pull",
  "level": "beginner",
  "mechanic": "isolation",
  "equipment": "machine",
  "primaryMuscles": [
    "traps"
  ],
  "secondaryMuscles": [
    "shoulders"
  ],
  "instructions": [
    "With the bar at thigh level, load an appropriate weight.",
    "Stand with the bar behind you, taking a shoulder-width, pronated grip on the bar and unhook the weight. You should be standing up straight with your head and chest up and your arms extended. This will be your starting position.",
    "Initiate the movement by shrugging your shoulders straight up. Do not flex the arms or wrist during the movement.",
    "After a brief pause return the weight to the starting position.",
    "Repeat for the desired number of repetitions before engaging the hooks to rack the weight."
  ],
  "category": "strength",
  "images": [
    "Smith_Machine_Behind_the_Back_Shrug/0.jpg",
    "Smith_Machine_Behind_the_Back_Shrug/1.jpg"
  ],
  "id": "smith_machine_behind_the_back_shrug"
}

=== gfauredev/free-exercise-db/exercises/Flutter_Kicks.json
{
  "name": "Flutter Kicks",
  "force": "pull",
  "level": "beginner",
  "mechanic": "compound",
  "primaryMuscles": [
    "glutes"
  ],
  "secondaryMuscles": [
    "hamstrings"
  ],
  "instructions": [
    "On a flat bench lie facedown with the hips on the edge of the bench, the legs straight with toes high off the floor and with the arms on top of the bench holding on to the front edge.",
    "Squeeze your glutes and hamstrings and straighten the legs until they are level with the hips. This will be your starting position.",
    "Start the movement by lifting the left leg higher than the right leg.",
    "Then lower the left leg as you lift the right leg.",
    "Continue alternating in this manner (as though you are doing a flutter kick in water) until you have done the recommended amount of repetitions for each leg. Make sure that you keep a controlled movement at all times. Tip: You will breathe normally as you perform this movement."
  ],
  "category": "strength",
  "images": [
    "Flutter_Kicks/0.jpg",
    "Flutter_Kicks/1.jpg"
  ],
  "id": "flutter_kicks"
}

=== gfauredev/free-exercise-db/exercises/kettlebell_seesaw_press.json
{
  "name": "Kettlebell Seesaw Press",
  "force": "push",
  "level": "intermediate",
  "mechanic": "compound",
  "equipment": "kettlebells",
  "primaryMuscles": [
    "shoulders"
  ],
  "secondaryMuscles": [
    "triceps"
  ],
  "instructions": [
    "Clean two kettlebells two your shoulders.",
    "Press one kettlebell.",
    "Lower the kettlebell and immediately press the other kettlebell. Make sure to do the same amount of reps on both sides."
  ],
  "category": "strength",
  "images": [
    "kettlebell_seesaw_press/0.jpg",
    "kettlebell_seesaw_press/1.jpg"
  ],
  "id": "kettlebell_seesaw_press"
}

=== gfauredev/free-exercise-db/exercises/Middle_Back_Stretch.json
{
  "name": "Middle Back Stretch",
  "force": "static",
  "level": "beginner",
  "mechanic": "isolation",
  "primaryMuscles": [
    "middle back"
  ],
  "secondaryMuscles": [
    "abdominals",
    "lats",
    "lower back"
  ],
  "instructions": [
    "Stand so your feet are shoulder width apart and your hands are on your hips.",
    "Twist at your waist until you feel a stretch. Hold for 10 to 15 seconds, then twist to the other side."
  ],
  "category": "stretching",
  "images": [
    "Middle_Back_Stretch/0.jpg",
    "Middle_Back_Stretch/1.jpg"
  ],
  "id": "middle_back_stretch"
}

=== gfauredev/free-exercise-db/exercises/Trap_Bar_Deadlift.json
{
  "name": "Trap Bar Deadlift",
  "force": "pull",
  "level": "beginner",
  "mechanic": "compound",
  "equipment": "other",
  "primaryMuscles": [
    "quadriceps"
  ],
  "secondaryMuscles": [
    "glutes",
    "hamstrings"
  ],
  "instructions": [
    "For this exercise load a trap bar, also known as a hex bar, to an appropriate weight resting on the ground. Stand in the center of the apparatus and grasp both handles.",
    "Lower your hips, look forward with your head and keep your chest up.",
    "Begin the movement by driving through the heels and extend your hips and knees. Avoid rounding your back at all times.",
    "At the completion of the movement, lower the weight back to the ground under control."
  ],
  "category": "strength",
  "images": [
    "Trap_Bar_Deadlift/0.jpg",
    "Trap_Bar_Deadlift/1.jpg"
  ],
  "id": "trap_bar_deadlift"
}

=== gfauredev/free-exercise-db/exercises/Dumbbell_Side_Bend.json
{
  "name": "Dumbbell Side Bend",
  "force": "pull",
  "level": "beginner",
  "mechanic": "isolation",
  "equipment": "dumbbell",
  "primaryMuscles": [
    "abdominals"
  ],
  "secondaryMuscles": [],
  "instructions": [
    "Stand up straight while holding a dumbbell on the left hand (palms facing the torso) as you have the right hand holding your waist. Your feet should be placed at shoulder width. This will be your starting position.",
    "While keeping your back straight and your head up, bend only at the waist to the right as far as possible. Breathe in as you bend to the side. Then hold for a second and come back up to the starting position as you exhale. Tip: Keep the rest of the body stationary.",
    "Now repeat the movement but bending to the left instead. Hold for a second and come back to the starting position.",
    "Repeat for the recommended amount of repetitions and then change hands."
  ],
  "category": "strength",
  "images": [
    "Dumbbell_Side_Bend/0.jpg",
    "Dumbbell_Side_Bend/1.jpg"
  ],
  "id": "dumbbell_side_bend"
}

=== gfauredev/free-exercise-db/exercises/Landmine_180s.json
{
  "name": "Landmine 180's",
  "force": "pull",
  "level": "beginner",
  "mechanic": "compound",
  "equipment": "barbell",
  "primaryMuscles": [
    "abdominals"
  ],
  "secondaryMuscles": [
    "glutes",
    "lower back",
    "shoulders"
  ],
  "instructions": [
    "Position a bar into a landmine or securely anchor it in a corner. Load the bar to an appropriate weight.",
    "Raise the bar from the floor, taking it to shoulder height with both hands with your arms extended in front of you. Adopt a wide stance. This will be your starting position.",
    "Perform the movement by rotating the trunk and hips as you swing the weight all the way down to one side. Keep your arms extended throughout the exercise.",
    "Reverse the motion to swing the weight all the way to the opposite side.",
    "Continue alternating the movement until the set is complete."
  ],
  "category": "strength",
  "images": [
    "Landmine_180s/0.jpg",
    "Landmine_180s/1.jpg"
  ],
  "id": "landmine_180s"
}
