=== gfauredev/free-exercise-db/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[0-9a-z_]+$"
    },
    "name": {
      "type": "string"
    },
    "force": {
      "type": "string",
      "enum": [
        "static",
        "pull",
        "push"
      ]
    },
    "level": {
      "type": "string",
      "enum": [
        "beginner",
        "intermediate",
        "expert"
      ]
    },
    "mechanic": {
      "type": "string",
      "enum": [
        "isolation",
        "compound"
      ]
    },
    "equipment": {
      "type": "string",
      "enum": [
        "medicine ball",
        "dumbbell",
        "bands",
        "kettlebells",
        "foam roll",
        "cable",
        "machine",
        "barbell",
        "exercise ball",
        "e-z curl bar",
        "other"
      ]
    },
    "primaryMuscles": {
      "type": "array",
      "items": [
        {
          "type": "string",
          "enum": [
            "abdominals",
            "abductors",
            "adductors",
            "biceps",
            "calves",
            "chest",
            "forearms",
            "glutes",
            "hamstrings",
            "lats",
            "lower back",
            "middle back",
            "neck",
            "quadriceps",
            "shoulders",
            "traps",
            "triceps"
          ]
        }
      ]
    },
    "secondaryMuscles": {
      "type": "array",
      "items": [
        {
          "type": "string",
          "enum": [
            "abdominals",
            "abductors",
            "adductors",
            "biceps",
            "calves",
            "chest",
            "forearms",
            "glutes",
            "hamstrings",
            "lats",
            "lower back",
            "middle back",
            "neck",
            "quadriceps",
            "shoulders",
            "traps",
            "triceps"
          ]
        }
      ]
    },
    "instructions": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "category": {
      "type": "string",
      "enum": [
        "powerlifting",
        "strength",
        "stretching",
        "cardio",
        "olympic weightlifting",
        "strongman",
        "plyometrics"
      ]
    },
    "images": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "id",
    "name",
    "force",
    "level",
    "mechanic",
    "primaryMuscles",
    "secondaryMuscles",
    "instructions",
    "category",
    "images"
  ]
}

=== gfauredev/free-exercise-db/exercises/tuck_crunch.json
{
  "name": "Tuck Crunch",
  "force": "pull",
  "level": "beginner",
  "mechanic": "isolation",
  "primaryMuscles": [
    "abdominals"
  ],
  "secondaryMuscles": [],
  "instructions": [
    "To begin, lie down on the floor or an exercise mat with your back pressed against the floor. Your arms should be lying across your sides with the palms facing down.",
    "Your legs should be crossed by wrapping one ankle around the other. Slowly elevate your legs up in the air until your thighs are perpendicular to the floor with a slight bend at the knees. Note: Your knees and toes should be parallel to the floor as opposed to the thighs.",
    "Move your arms from the floor and cross them so they are resting on your chest. This is the starting position.",
    "While keeping your lower back pressed against the floor, slowly lift your torso. Remember to exhale while perform this part of the exercise.",
    "Slowly begin to lower your torso back down to the starting position while inhaling.",
    "Repeat for the recommended amount of repetitions."
  ],
  "category": "strength",
  "images": [
    "tuck_crunch/0.jpg",
    "tuck_crunch/1.jpg"
  ],
  "id": "tuck_crunch"
}

=== gfauredev/free-exercise-db/exercises/Cable_Wrist_Curl.json
{
  "name": "Cable Wrist Curl",
  "force": "pull",
  "level": "beginner",
  "mechanic": "isolation",
  "equipment": "cable",
  "primaryMuscles": [
    "forearms"
  ],
  "secondaryMuscles": [],
  "instructions": [
    "Start out by placing a flat bench in front of a low pulley cable that has a straight bar attachment.",
    "Use your arms to grab the cable bar with a narrow to shoulder width supinated grip (palms up) and bring them up so that your forearms are resting against the top of your thighs. Your wrists should be hanging just beyond your knees.",
    "Start out by curling your wrist upwards and exhaling. Keep the contraction for a second.",
    "Slowly lower your wrists back down to the starting position while inhaling.",
    "Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.",
    "Repeat for the recommended amount of repetitions."
  ],
  "category": "strength",
  "images": [
    "Cable_Wrist_Curl/0.jpg",
    "Cable_Wrist_Curl/1.jpg"
  ],
  "id": "cable_wrist_curl"
}

=== gfauredev/free-exercise-db/exercises/mountain_climber.json
{
  "name": "Mountain Climber",
  "force": "pull",
  "level": "beginner",
  "mechanic": "compound",
  "primaryMuscles": [
    "quadriceps"
  ],
  "secondaryMuscles": [
    "chest",
    "hamstrings",
    "shoulders"
  ],
  "instructions": [
    "Begin in a pushup position, with your weight supported by your hands and toes. Flexing the knee and hip, bring one leg until the knee is approximately under the hip. This will be your starting position.",
    "Explosively reverse the positions of your legs, extending the bent leg until the leg is straight and supported by the toe, and bringing the other foot up with the hip and knee flexed. Repeat in an alternating fashion for 20-30 seconds."
  ],
  "category": "plyometrics",
  "images": [
    "mountain_climber/0.jpg",
    "mountain_climber/1.jpg"
  ],
  "id": "mountain_climber"
}

=== gfauredev/free-exercise-db/exercises/bent_arm_dumbbell_pullover.json
{
  "name": "Bent-Arm Dumbbell Pullover",
  "force": "push",
  "level": "intermediate",
  "mechanic": "compound",
  "equipment": "dumbbell",
  "primaryMuscles": [
    "chest"
  ],
  "secondaryMuscles": [
    "lats",
    "shoulders",
    "triceps"
  ],
  "instructions": [
    "Place a dumbbell standing up on a flat bench.",
    "Ensuring that the dumbbell stays securely placed at the top of the bench, lie perpendicular to the bench (torso across it as in forming a cross) with only your shoulders lying on the surface. Hips should be below the bench and legs bent with feet firmly on the floor. The head will be off the bench as well.",
    "Grasp the dumbbell with both hands and hold it straight over your chest with a bend in your arms. Both palms should be pressing against the underside one of the sides of the dumbbell. This will be your starting position. Caution: Always ensure that the dumbbell used for this exercise is secure. Using a dumbbell with loose plates can result in the dumbbell falling apart and falling on your face.",
    "While keeping your arms locked in the bent arm position, lower the weight slowly in an arc behind your head while breathing in until you feel a stretch on the chest.",
    "At that point, bring the dumbbell back to the starting position using the arc through which the weight was lowered and exhale as you perform this movement.",
    "Hold the weight on the initial position for a second and repeat the motion for the prescribed number of repetitions."
  ],
  "category": "strength",
  "images": [
    "bent_arm_dumbbell_pullover/0.avif",
    "bent_arm_dumbbell_pullover/1.avif"
  ],
  "id": "bent_arm_dumbbell_pullover"
}

=== gfauredev/free-exercise-db/exercises/push_up_with_feet_elevated.json
{
  "name": "Push-Up With Feet Elevated",
  "force": "push",
  "level": "beginner",
  "mechanic": "compound",
  "primaryMuscles": [
    "chest"
  ],
  "secondaryMuscles": [
    "shoulders",
    "triceps"
  ],
  "instructions": [
    "Lie on the floor face down and place your hands about 36 inches apart from each other holding your torso up at arms length.",
    "Place your toes on top of a flat bench. This will allow your body to be elevated. Note: The higher the elevation of the flat bench, the higher the resistance of the exercise is.",
    "Lower yourself until your chest almost touches the floor as you inhale.",
    "Using your pectoral muscles, press your upper body back up to the starting position and squeeze your chest. Breathe out as you perform this step.",
    "After a second pause at the contracted position, repeat the movement for the prescribed amount of repetitions."
  ],
  "category": "strength",
  "images": [
    "push_up_with_feet_elevated/0.jpg",
    "push_up_with_feet_elevated/1.jpg"
  ],
  "id": "push_up_with_feet_elevated"
}

=== gfauredev/free-exercise-db/exercises/reverse_barbell_curl.json
{
  "name": "Reverse Barbell Curl",
  "force": "pull",
  "level": "beginner",
  "mechanic": "isolation",
  "equipment": "barbell",
  "primaryMuscles": [
    "biceps"
  ],
  "secondaryMuscles": [
    "forearms"
  ],
  "instructions": [
    "Stand up with your torso upright while holding a barbell at shoulder width with the elbows close to the torso. The palm of your hands should be facing down (pronated grip). This will be your starting position.",
    "While holding the upper arms stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second as you squeeze the muscle.",
    "Slowly begin to bring the bar back to starting position as your breathe in.",
    "Repeat for the recommended amount of repetitions."
  ],
  "category": "strength",
  "images": [
    "reverse_barbell_curl/0.avif",
    "reverse_barbell_curl/1.avif"
  ],
  "id": "reverse_barbell_curl"
}

=== gfauredev/free-exercise-db/exercises/Seated_Side_Lateral_Raise.json
{
  "name": "Seated Side Lateral Raise",
  "force": "push",
  "level": "beginner",
  "mechanic": "isolation",
  "equipment": "dumbbell",
  "primaryMuscles": [
    "shoulders"
  ],
  "secondaryMuscles": [],
  "instructions": [
    "Pick a couple of dumbbells and sit at the end of a flat bench with your feet firmly on the floor. Hold the dumbbells with your palms facing in and your arms straight down at your sides at arms' length. This will be your starting position.",
    "While maintaining the torso stationary (no swinging), lift the dumbbells to your side with a slight bend on the elbow and the hands slightly tilted forward as if pouring water in a glass. Continue to go up until you arms are parallel to the floor. Exhale as you execute this movement and pause for a second at the top.",
    "Lower the dumbbells back down slowly to the starting position as you inhale.",
    "Repeat for the recommended amount of repetitions."
  ],
  "category": "strength",
  "images": [
    "Seated_Side_Lateral_Raise/0.jpg",
    "Seated_Side_Lateral_Raise/1.jpg"
  ],
  "id": "seated_side_lateral_raise"
}

=== gfauredev/free-exercise-db/exercises/dumbbell_alternate_bicep_curl.json
{
  "name": "Dumbbell Alternate Bicep Curl",
  "force": "pull",
  "level": "beginner",
  "mechanic": "isolation",
  "equipment": "dumbbell",
  "primaryMuscles": [
    "biceps"
  ],
  "secondaryMuscles": [
    "forearms"
  ],
  "instructions": [
    "Stand (torso upright) with a dumbbell in each hand held at arms length. The elbows should be close to the torso and the palms of your hand should be facing your thighs.",
    "While holding the upper arm stationary, curl the right weight as you rotate the palm of the hands until they are facing forward. At this point continue contracting the biceps as you breathe out until your biceps is fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps. Tip: Only the forearms should move.",
    "Slowly begin to bring the dumbbell back to the starting position as your breathe in. Tip: Remember to twist the palms back to the starting position (facing your thighs) as you come down.",
    "Repeat the movement with the left hand. This equals one repetition.",
    "Continue alternating in this manner for the recommended amount of repetitions."
  ],
  "category": "strength",
  "images": [
    "dumbbell_alternate_bicep_curl/0.jpg",
    "dumbbell_alternate_bicep_curl/1.jpg"
  ],
  "id": "dumbbell_alternate_bicep_curl"
}
